### ISSUE TITLE
Create a student_detail tempate

### ISSUE THREAD

**Issue by marceloFA** [marceloFA/deadlines_app#14]
Currently a Student has a simple profile page, the topic of this issue is improving the perofile page
Some elements the page could have:
- [X] Basic Student info
- [x] A list of all the tasks a Student is currently assigned to
- [x] a listing of all submissions including this student
- [x] A link to Student edit profile as a button (we currently have no edit page for this)
- [x] A button to deactivate a student account

**Comment by ambarmendez** [comment]
@marceloFA on it! :relaxed:

**Comment by marceloFA** [comment]
@ambarmendez, some parta of this issue are already resolved. I'm updating the description right now

**Comment by ambarmendez** [comment]
A list of all the tasks per student is ready as well.

![tasks_per_user](https://user-images.githubusercontent.com/23302056/66284457-88c87600-e913-11e9-93a3-7dc1c7de01de.jpg)

Unless this is not what you are referring to. Please @marceloFA, let me know meanwhile I'm working on the nest issue.
