### ISSUE TITLE
Task can be marked as done

### ISSUE THREAD

**Issue by marceloFA** [marceloFA/deadlines_app#15]
This could be implemented as a new field in the Task model as a BooleanField and a button on the task_detail page so a Student can mark it as done

**Comment by DustinTheGreat** [comment]
Why would this go in the User model and not the Task model?

**Comment by marceloFA** [comment]
My mistake, I updated the description

**Comment by DustinTheGreat** [comment]
mind if I make a pull for this?

**Comment by marceloFA** [comment]
That'd be very good!
