### ISSUE TITLE
Add task progression bar to each task on task list

### ISSUE THREAD

**Issue by marceloFA** [marceloFA/deadlines_app#28]
**Is your feature request related to a problem? Please describe.**
A good task list template can very pleasant to new users. This issue has the intention of adding the task completion bar present on the task details template also on the tasks list

**Describe the solution you'd like**
Every task on the list would have its progression bar. Including past tasks. The progression bar could be added as a new column on the table that currently presents the tasks on this task list template.

**Describe alternatives**
A good altermative to this would be adding badges to each task on the list and coloring the badges according to the progression colors we already have.

**Additional context**
This must be implemented as simply and as nicer it could be, bootstrap is included in this project and can certainly be used for this

**Comment by Krishna-Sivakumar** [comment]
Could I work on this?

**Comment by marceloFA** [comment]
You can work on this, for sure, but remember the definitions for solving this issue (the ones I proposed up here on the description). Stay with the colors we already defined. @Krishna-Sivakumar
