### ISSUE TITLE
Add task_list template tables a sorting feature

### ISSUE THREAD

**Issue by marceloFA** [marceloFA/deadlines_app#39]
**Is your feature request related to a problem? Please describe.**
This is not related to a problem. This is related to an additional feature we could have on the task_list template (current homepage). Adding a sort feature to the tables on this page would be very nice

**Describe the solution you'd like**
As we're using [django-bootstrap](https://pypi.org/project/django-bootstrap4/) for styling we already have included jquery so we could use something like [data tables](https://datatables.net/examples/styling/bootstrap4) for this

**Describe alternatives you've considered**
We could also implement this feature manually if it's convenient to do so

**Comment by sonicaks** [comment]
Please check PR #40

**Comment by sonicaks** [comment]
@marceloFA any update on the PR?
