### ISSUE TITLE
cannot delete event

### ISSUE THREAD

**Issue by anapf9** [marceloFA/deadlines_app#43]
Request Method: | GET
-- | --
http://192.168.1.2:8000/events/delete/2
2.2.6
FieldError
Cannot resolve keyword 'students' into field. Choices are: created_at, deadline, id, name, qualis, submissions, updated_at, url
/usr/local/lib/python3.8/site-packages/django/db/models/sql/query.py in names_to_path, line 1419
/usr/local/bin/python
3.8.1
['/deadlines_app',  '/usr/local/lib/python38.zip',  '/usr/local/lib/python3.8',  '/usr/local/lib/python3.8/lib-dynload',  '/usr/local/lib/python3.8/site-packages']
Mon, 13 Jan 2020 13:31:52 +0000

**Comment by marceloFA** [comment]
85626cc fixes this
