### ISSUE TITLE
Task deletion feature is not fully implemented

### ISSUE THREAD

**Issue by marceloFA** [marceloFA/deadlines_app#6]
in the task_detail template there's a button to the Task in question. This button is currently not working. Part of the view logic for this is already implemented in the task_delted method inside tasks.views.

**Comment by marier-nico** [comment]
Hey, I think I could work on this!

**Comment by BusinessFawn** [comment]
Am I crazy for thinking this is a one line change?

line 80: task = `get_object_or_404(Task, pk=pk, students=request.user)`

**Comment by marier-nico** [comment]
@BusinessFawn Yeah, that seems to do it :slightly_smiling_face:

**Comment by BusinessFawn** [comment]
All yours :)

Happy Hacking!

**Comment by marier-nico** [comment]
@BusinessFawn Thanks a bunch, same to you!

**Comment by marceloFA** [comment]
I didn't noticed this was such a simple issue to be solved :D
Please submit a PR for this fix if you're looking for hacktoberfest points
