### ISSUE TITLE
When a Task is already passed, the progres bar in task_detail must behave accordingly

### ISSUE THREAD

**Issue by marceloFA** [marceloFA/deadlines_app#9]
The progress bar could have colors accordingly to the percentage of task completion, like this:
Green: 0%69%
Yellow: 70%->89%
Red: 90% -> 99%
bootstrap 'info' color (hex code is #5bc0de) : 100%

**Comment by marceloFA** [comment]
![behaviour](https://user-images.githubusercontent.com/29216027/66093993-ba82bb00-e568-11e9-9c5c-64cac3941b60.png) This is the expected behaviour (noticed that a Task is outdated when the days left field has a negative count)

**Comment by BusinessFawn** [comment]
I'll take a look.

**Comment by BusinessFawn** [comment]
Were you interested in having a green -> yellow -> red progression within the count down?

Green: 0%-70%
Yellow: 71%-100%
Red: Negative days

I can also do:
Green: 0%-100%
Red: Negative days

**Comment by marceloFA** [comment]
Would you do like this, please?
Green: 0%-70%
Yellow: 71%->89%
Red: 90% -> 100%
bootstrap 'info' color (hex code is #5bc0de) : Any number of negative days

I'll update the issue according to this new color scheme

**Comment by marceloFA** [comment]
I changed my mind after realizing that red for a negative count of days didn't make much sense

**Comment by BusinessFawn** [comment]
Made a small PR for this behavior.

0%-69% = green
70%-89% = yellow
90%-99% = red
100% = blue
